packages/react/example/package-lock.json, packages/react/example/package.json
=> ci(react): react examples should not be published

.circleci/config.yml
=> test(react): fix verify release script

.circleci/config.yml
=> ci: install top level dependencies

packages/webdriverjs/package.json
=> chore(webdriverio): make webdriverio private

packages/puppeteer/src/axePuppeteer.ts
=> fix(puppeteer): check to see if frame exist before injecting JS

packages/webdriverio/package.json, packages/webdriverjs/package.json
=> chore: make webdriverio private not webdriverjs

packages/cli/README.md, packages/webdriverjs/README.md
Making sure to [capture this change](https://github.com/dequelabs/axe-webdriverjs/pull/153/files) for the new repo
=> docs: update link to selenium webdriver

packages/cli/package-lock.json, packages/webdriverjs/package-lock.json
=> chore: update chromedriver to use v86 for webdriver and cli

README.md
=> docs(readme): add slack badge

packages/puppeteer/package-lock.json, packages/puppeteer/package.json
=> chore(puppeteer): update to support `puppeteer@latest`

.circleci/config.yml
=> ci: update production release to use `from-package` option

packages/react/package-lock.json, packages/react/package.json
=> chore(react): update axe-core to v4.1.0

.circleci/config.yml
=> ci: run `axe-core-test` on `/^release*/` and master branches

packages/cli/package-lock.json, packages/cli/package.json
Blocked by: https://github.com/dequelabs/axe-core-npm/pull/161
=> chore(cli): update axe-core to v4.1.0

packages/puppeteer/README.md
See: https://github.com/dequelabs/axe-core-npm/issues/168
=> docs(puppeteer): remove broken link

packages/cli/package-lock.json, packages/cli/package.json, packages/puppeteer/package-lock.json, packages/puppeteer/package.json, packages/react/package-lock.json, packages/react/package.json, packages/reporter-earl/package-lock.json, packages/reporter-earl/package.json, packages/webdriverio/package-lock.json, packages/webdriverjs/package-lock.json, packages/webdriverjs/package.json
=> chore: update all packages to use axe-core@4.1.1

packages/webdriverjs/lib/axe-injector.js
=> chore(webdriverjs): fix incorrect comment

packages/react/index.ts, packages/react/test/index.ts
=> fix(react): handle undefined config

packages/react/cypress/integration/index-test.js, packages/react/test/index.ts
=> test(react): add test for when config is undefined/null

packages/cli/package-lock.json, packages/react/examples/next.js/package-lock.json, packages/react/examples/shadow-dom/package-lock.json, packages/react/index.ts, packages/webdriverjs/package-lock.json
Description:
version: `4.1.0`
I was getting the error `TypeError: Cannot read property 'runOnly' of undefined` from this line:
`axe.default(React, ReactDom, 1000);`
The solution was similar to [this author's solution](https://github.com/dequelabs/axe-core-npm/issues/157#issuecomment-758724273), therefore perhaps they are related?
=> fix: `conf` defaults to `{}`

packages/cli/package-lock.json
=> chore(cli): regenerate package-lock.json file

packages/webdriverio/src/index.ts
See: https://github.com/dequelabs/axe-core-npm/issues/75
=> chore(webdriverio): fix `switchToParentFrame()`

packages/cli/package-lock.json, packages/cli/package.json, packages/reporter-earl/package-lock.json, packages/webdriverio/package-lock.json, packages/webdriverio/package.json, packages/webdriverjs/package-lock.json, packages/webdriverjs/package.json
=> chore: update chromedriver to use v90 for webdriver and cli

packages/webdriverio/src/index.ts, packages/webdriverio/src/test.ts
=> fix(webdriverio): inject axe-core branding into all iframes

.github/PULL_REQUEST_TEMPLATE.md, .github/review.yml
=> chore: add security review

.github/ISSUE_TEMPLATE.md
=> docs: add issues template

packages/cli/src/bin/cli.test.ts, packages/cli/src/lib/axe-test-urls.ts
=> fix(cli): add `endTimer()` for page load timer

README.md
=> docs: add more information about packages in mono-repo

packages/puppeteer/package-lock.json, packages/puppeteer/package.json, packages/puppeteer/src/axePuppeteer.ts, packages/puppeteer/src/browser.ts
=> feat(puppeteer): support puppeteer v9

CHANGELOG.md, lerna.json, packages/cli/CHANGELOG.md, packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/lib/axe-test-urls.ts, packages/puppeteer/CHANGELOG.md, packages/puppeteer/package-lock.json, packages/puppeteer/package.json, packages/react/CHANGELOG.md, packages/react/examples/next.js/package-lock.json, packages/react/examples/shadow-dom/CHANGELOG.md, packages/react/examples/shadow-dom/package-lock.json, packages/react/examples/shadow-dom/package.json, packages/react/package-lock.json, packages/react/package.json, packages/reporter-earl/CHANGELOG.md, packages/reporter-earl/package-lock.json, packages/reporter-earl/package.json, packages/webdriverio/CHANGELOG.md, packages/webdriverio/package-lock.json, packages/webdriverio/package.json, packages/webdriverjs/CHANGELOG.md, packages/webdriverjs/package-lock.json, packages/webdriverjs/package.json
Blocked by: https://github.com/dequelabs/axe-core-npm/pull/258
=> chore: release v4.2.1

packages/playwright/package.json
See: https://github.com/dequelabs/axe-core-npm/pull/263#discussion_r646680440
=> fix(playwright): Make package public

.github/workflows/sync-master-develop.yml
Same as https://github.com/dequelabs/axe-core/pull/2975
=> ci: Fix sync branches workflow

packages/cli/src/lib/webdriver.test.ts, packages/cli/src/lib/webdriver.ts, packages/react/README.md, packages/react/index.ts
Cherry-picking commits from #260 to get CircleCI to run properly.
=> feat(react): Add configuration option to optional disable cache (deduplication)

packages/cli/package.json, packages/playwright/package.json, packages/reporter-earl/package.json, packages/webdriverio/package.json, packages/webdriverjs/package.json
- https://github.com/dequelabs/axe-core-npm/issues/311
=> Chore: Added repository property to missing packages package.json files

packages/webdriverjs/package-lock.json, packages/webdriverjs/package.json, packages/webdriverjs/src/browser.ts, packages/webdriverjs/src/index.ts, packages/webdriverjs/tests/axe-webdriverjs.spec.ts
=> chore(wdjs): call finishRun in about:blank

packages/webdriverio/src/index.ts, packages/webdriverio/src/utils.ts
See: https://github.com/dequelabs/axe-core-npm/issues/343#issuecomment-910338562
=> chore(webdriverio): use native webdriverio methods to open window

packages/webdriverio/package-lock.json, packages/webdriverio/package.json, packages/webdriverio/src/index.ts, packages/webdriverio/src/test.ts, packages/webdriverio/src/types.ts, packages/webdriverio/src/utils.ts
Adds support for WDIO v7. This changes the types over to use v7's types. Using axe-core/webdriverio v4.3 with wdio v6 will now see `any` as the argument for `client`.
=> feat(wdio): Upgrade to support, and use types of v7

packages/playwright/error-handling.md, packages/puppeteer/error-handling.md, packages/webdriverio/error-handling.md, packages/webdriverjs/error-handling.md
add error markdown file for all npm packages
=> docs: add error markdown to all packages

packages/playwright/README.md
closes issue: https://github.com/dequelabs/axe-core-npm/issues/396
=> docs(playwright): update docs to show include/exclude chaining

packages/playwright/package.json, packages/webdriverio/package.json, packages/webdriverio/tsconfig.json, packages/webdriverjs/package.json
See: https://github.com/dequelabs/axe-core-npm/issues/376
=> chore: only package required dist dir

packages/webdriverjs/README.md
=> docs(webdriverjs): change `Getting Started` docs consistent with webdriverio

packages/puppeteer/package-lock.json, packages/puppeteer/package.json
=> chore: support puppeteer version 13

packages/react/README.md
closes issue: https://github.com/dequelabs/axe-core-npm/issues/475
=> chore(react): update docs link shadow-dom example

axe_core_test/package-lock.json, package-lock.json, packages/cli/package-lock.json, packages/cli/package.json, packages/playwright/package-lock.json, packages/puppeteer/package-lock.json, packages/react/examples/next.js/package-lock.json, packages/react/examples/shadow-dom/package-lock.json, packages/react/package-lock.json, packages/reporter-earl/package-lock.json, packages/webdriverio/package-lock.json, packages/webdriverjs/package-lock.json, packages/webdriverjs/package.json, packages/webdriverjs/tests/example/package-lock.json
=> chore: update selenium version

packages/react/package.json
https://github.com/dequelabs/axe-core-npm/issues/519
I've verified that this works manually by placing the file in the `node_modules` myself, after which everything runs as intended.
=> feat: include missing cache file

packages/puppeteer/package-lock.json, packages/puppeteer/package.json, packages/puppeteer/test/axePuppeteer.test.ts
=> fix: update to support puppeteer v14

packages/react/README.md
Greenkeeper service no longer active
=> docs(react): Update README.md to remove Greenkeeper badge

packages/cli/src/bin/cli.test.ts, packages/cli/src/bin/cli.ts, packages/cli/src/bin/index.ts
=> fix(cli): display stack trace on errors by default

packages/cli/package.json, packages/cli/tsconfig.json
see: https://github.com/dequelabs/axe-devtools-npm/issues/1611
=> fix: provide proper typings for axe-cli

packages/playwright/src/index.ts, packages/playwright/tests/axe-playwright.spec.ts, packages/puppeteer/src/axePuppeteer.ts, packages/puppeteer/test/axePuppeteer.test.ts, packages/webdriverio/src/index.ts, packages/webdriverio/src/test.ts, packages/webdriverjs/src/index.ts, packages/webdriverjs/tests/axe-webdriverjs.spec.ts
=> chore: make errorUrl configurable

packages/playwright/package-lock.json, packages/playwright/package.json, packages/playwright/src/index.ts, packages/playwright/src/types.ts
=> fix: change `playwright` to devdep and use `playwright-core` types

packages/cli/package-lock.json, packages/cli/package.json, packages/playwright/package-lock.json, packages/playwright/package.json, packages/puppeteer/package-lock.json, packages/puppeteer/package.json, packages/reporter-earl/package-lock.json, packages/reporter-earl/package.json, packages/webdriverio/package-lock.json, packages/webdriverio/package.json, packages/webdriverjs/package-lock.json, packages/webdriverjs/package.json
=> chore: update to use axe-core 4.4.3

CODE_OF_CONDUCT.md
[rendered](https://github.com/dequelabs/axe-core-npm/pull/570/files?short_path=ffdbe3a#diff-ffdbe3a1e7ee93cacfc080b6c635ccf3a8f6b0f00f2fb884f78c6b5f9dac8fd2)
=> docs: add `CODE_OF_CONDUCT.md`

packages/puppeteer/README.md
=> docs(puppeteer): unable to inject axe-core when js is disabled

.circleci/config.yml, packages/webdriverio/package-lock.json, packages/webdriverio/package.json, packages/webdriverio/src/index.ts, packages/webdriverio/src/test.ts, packages/webdriverio/src/types.ts, packages/webdriverio/src/utils.ts
Closes: https://github.com/dequelabs/axe-core-npm/issues/695
Closes: https://github.com/dequelabs/axe-core-npm/issues/705
=> feat: support WDIO v8

packages/puppeteer/esmTest.mjs, packages/puppeteer/package-lock.json, packages/puppeteer/package.json, packages/puppeteer/src/legacy.ts, packages/puppeteer/src/utils.ts, packages/webdriverio/esmTest.mjs, packages/webdriverio/package-lock.json, packages/webdriverio/package.json, packages/webdriverio/src/index.ts, packages/webdriverio/tsconfig.json
Closes: https://github.com/dequelabs/axe-core-npm/issues/717
=> fix: proper imports in esm context

.circleci/config.yml, packages/playwright/package-lock.json, packages/playwright/package.json, packages/playwright/src/index.ts, packages/playwright/tests/axe-playwright.spec.ts
Resolves the error `Please install @playwright/test package to use Playwright Test.`.
See https://github.com/microsoft/playwright/issues/23098.
Also removes a few unused variables.
=> fix(playwright): use @playwright/test

packages/cli/package-lock.json, packages/cli/package.json, packages/webdriverio/package-lock.json, packages/webdriverio/package.json, packages/webdriverjs/package-lock.json, packages/webdriverjs/package.json
Ref: https://app.circleci.com/pipelines/github/dequelabs/axe-core-npm/1655/workflows/380945e2-a0b4-4dd3-afc8-b3702c7468ed/jobs/13669
=> chore: update chromedriver

packages/playwright/README.md, packages/playwright/example.js, packages/playwright/package.json, packages/playwright/src/index.ts, packages/playwright/test/axe-playwright.spec.ts, packages/puppeteer/README.md, packages/puppeteer/example.js, packages/puppeteer/test/axe-puppeteer.spec.ts, packages/webdriverio/README.md, packages/webdriverio/example.js, packages/webdriverio/src/index.ts, packages/webdriverio/test/axe-webdriverio.spec.ts, packages/webdriverjs/README.md, packages/webdriverjs/example.js, packages/webdriverjs/src/index.ts, packages/webdriverjs/test/axe-webdriverjs.spec.ts
Also made the docs consistent between packages (same url, same structure, etc.) and made the tests use the named import
=> docs: update docs to use named import and create example.js

.github/workflows/auto-patch-release.yml
https://github.com/dequelabs/axe-api-team/issues/333
=> ci: auto patch-release every 2 weeks

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/possible-bug.yml, .github/ISSUE_TEMPLATE/question.yml
shamelessly borrowed from https://github.com/dequelabs/axe-core/tree/develop/.github/ISSUE_TEMPLATE
=> chore: add `ISSUE_TEMPLATES`

README.md, package.json
=> docs: update development instructions for npm workspace

package-lock.json, packages/cli/package.json, packages/playwright/package.json, packages/puppeteer/package.json, packages/react/package.json, packages/reporter-earl/package.json, packages/webdriverio/package.json, packages/webdriverjs/package.json
=> fix: pin axe-core version to accept patch updates only

packages/cli/package.json
=> fix(cli): include required files when publishing

.github/dependabot.yml
=> ci: add dependabot workflow

.github/workflows/auto-patch-release.yml, .github/workflows/create-release-candidate.yml, .github/workflows/create-release.yml, .github/workflows/deploy.yml, .github/workflows/semantic-pr-title.yml, .github/workflows/sync-master-develop.yml, .github/workflows/update-axe-core.yml
=> ci: add timeouts for each GHA workflow

package-lock.json, packages/cli/package.json, packages/playwright/package.json, packages/puppeteer/package.json, packages/react/package.json, packages/reporter-earl/package.json, packages/webdriverio/package.json, packages/webdriverjs/package.json
Reverts dequelabs/axe-core-npm#968
no qa required
=> Revert "fix: Update axe-core to v4.8.3"

.github/workflows/deploy.yml
Workflow: https://github.com/dequelabs/axe-core-npm/actions/runs/7533884562/job/20507250388
no qa required
=> ci: add env var required for creating gh releases

.github/workflows/deploy.yml
=> ci: fix github release script

.github/workflows/tests.yml, package-lock.json, packages/cli/src/lib/webdriver.test.ts
Chromedriver is failing here https://github.com/dequelabs/axe-core-npm/actions/runs/7798549140/job/21267495668?pr=1004 this PR should fix CI
no qa required
=> chore: update chromedriver to 121

.github/workflows/deploy.yml
=> ci: fix tagging when creating releases

packages/react/README.md
Closes #500.
Refs: #500 
QA notes: No QA needed.
=> docs(react): Update React support information

package-lock.json
=> fix: Update axe-core to v4.9.1

packages/cli/src/bin/index.ts
=> chore(cli): update deque university link to correct url

.github/workflows/deploy.yml, .github/workflows/tests.yml, .github/workflows/update-axe-core.yml
Closes https://github.com/dequelabs/bass-team/issues/176
No QA required
=> chore: update node to 22

packages/webdriverio/src/index.ts
=> fix(wdio): resolve blank navigation issue in WDIO v9

.github/dependabot.yml
In response to https://github.com/dequelabs/axe-core-npm/pull/1219
No QA required
=> chore: dont update react >17
