package.json

The root-level package.json's `fmt` and `lint` scripts were using single-quotes to encapsulate arguments, which works on linux but not windows. On Windows, the single quotes are treated as part of the argument, and so the glob patterns don't match anything. The old version gives an error like this:
```
> npm run lint
> axe-core-npm@ lint C:\repos\axe-core-npm
> eslint *.js 'packages/**/*.{js,ts,tsx}'
Oops! Something went wrong! :(
ESLint: 7.0.0
No files matching the pattern "'packages/**/*.{js,ts,tsx}'" were found.
Please check for typing mistakes in the pattern.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! axe-core-npm@ lint: `eslint *.js 'packages/**/*.{js,ts,tsx}'`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the axe-core-npm@ lint script.
npm ERR! This is probably not a …
```

chore: make root-level fmt and lint use cross-plat compatible quotes

---

packages/puppeteer/package-lock.json
packages/puppeteer/package.json

Blocked by: https://github.com/dequelabs/axe-core-npm/pull/161

chore(puppeteer): update axe-core to v4.1.0

---

packages/reporter-earl/package-lock.json
packages/reporter-earl/package.json

Blocked by: https://github.com/dequelabs/axe-core-npm/pull/161

chore(reporter-earl): update axe-core to v4.1.0

---

packages/webdriverjs/package-lock.json
packages/webdriverjs/package.json

Blocked by: https://github.com/dequelabs/axe-core-npm/pull/161

chore(webdriverjs): update axe-core to v4.1.0

---

packages/puppeteer/README.md

docs(puppeteer): add `disableFrames` method to docs

---

packages/webdriverio/README.md

See: https://github.com/dequelabs/axe-core-npm/issues/216

docs(webdriverio): change loglevel to error in example

---

package-lock.json
package.json
packages/cli/package-lock.json
packages/cli/package.json
packages/puppeteer/package-lock.json
packages/puppeteer/package.json
packages/puppeteer/src/axePuppeteer.ts
packages/puppeteer/src/browser.ts
packages/react/index.ts
packages/react/package-lock.json
packages/react/package.json
packages/reporter-earl/package-lock.json
packages/reporter-earl/package.json
packages/webdriverio/package-lock.json
packages/webdriverio/package.json
packages/webdriverio/src/index.ts
packages/webdriverjs/package-lock.json
packages/webdriverjs/package.json
packages/webdriverjs/src/axe-injector.ts

feat: update axe-core to 4.2.0

---

packages/cli/src/lib/axe-test-urls.ts

Partly addresses #230 
I discovered my CLI issue was because of the Content Security Policy (CSP) headers that I set in my web app. 
When I set `Content-Security-Policy` to `script-src 'unsafe-inline';`, AXE is then able to process the page.
This timeout is to force AXE to fail after 10 seconds of waiting; instead of indefinitely waiting for `.deque-axe-is-ready` (which will never be injected because of strict CSP headers in place).
**Sample output with timeout in place**
```console
Running axe-core 4.2.0 in chrome-headless
Testing http://example.com ... please wait, this may take a minute.
An error occurred while testing this page.
Please report the problem to: https://github.com/dequelabs/axe-cli/issues/
```

fix(cli): add timeout waiting for page to be ready

---

packages/cli/src/lib/webdriver.test.ts
packages/cli/src/lib/webdriver.ts
packages/cli/src/types.ts

This PR should address https://github.com/dequelabs/axe-core-npm/issues/248
It updates 3 files to change how arguments are passed:
- Removes a now unnecessary cast from `packages/cli/src/types.ts`
- Changes how options are passed in `packages/cli/src/lib/webdriver.ts`
- Modifies test for option passing to match new behavior in `packages/cli/src/lib/webdriver.test.ts`
- Adds a test for multiple args in `packages/cli/src/lib/webdriver.test.ts`

fix: pass chrome options to `chromeOptions.addArguments()` 

---

packages/react/README.md

Fixed example usage of envify link in the "[Initialize the module](https://www.npmjs.com/package/@axe-core/react)" section.

docs(react): fix envify example link

---

packages/webdriverio/src/index.ts
packages/webdriverio/src/test.ts

add frame testing from test fixtures
ref:https://github.com/dequelabs/axe-core-npm/issues/349

test(webdriverio): make sure to test `frame-tested`

---

packages/webdriverjs/src/index.ts
packages/webdriverjs/src/types.ts
packages/webdriverjs/src/utils/index.ts
packages/webdriverjs/tests/axe-webdriverjs.spec.ts
packages/webdriverjs/tests/fixtures/context.html
packages/webdriverjs/tests/fixtures/iframe-one.html

Added support for method chaining on include and include as well as iframe CSS selectors. 
Refactored the current include/exclude tests to check if the results include / exclude the correct class. Used a function from [Playwright](https://github.com/dequelabs/axe-core-npm/blob/develop/packages/playwright/tests/axe-playwright.spec.ts#L377) that returns the node targets within a string array.
Examples: 
```js
// include and exclude
const builder = new AxeBuilder(driver)
.include('.include')
.exclude('.exclude');
```
```js
// chaining include
const builder = new AxeBuilder(driver)
.include('.include')
.include('.include2');
```
```js
// chaining exclude
const builder = new AxeBuilder(driver)
.exclude('.exclude')
.exclude('.exclude2');
```
```js
// chaining include and exclude
const builder = …
```

fix(webdriverJS): include/exclude chaining and iframe selectors

---

.github/scripts/prepare_release.sh
.github/workflows/create-release.yml

No real way of testing this until it gets merged and the "Create Release" action can be used.
Requires the following variables added to secrets:
* CHANGELOG_VERSION - Used for changelog
* STD_VERSION_VERSION - Used for changelog
* ADT_API_RELEASE_NAME - Used only for git commit
* ADT_API_RELEASE_EMAIL - Used only for git commit

ci: add create-release workflow

---

packages/react/tsconfig.json

`@axe-core/react` dist folder contains generated `*.js.map` files with non-existing references to `.ts` files and can produce warnings e.g. see #414. This will ensure the source map files are inlined into `*.js.map` hence included in dist.
Closes #414.

@axe-core/react: includes source-maps to dist

---

packages/cli/src/bin/cli.test.ts
packages/cli/src/bin/index.ts

We were not passing the `--chromedriver-path` arg value to webdriver. 
Within `webdriver.ts` `config.chromedriverPath` would produce undefined even if `--chromedriver-path` was set which would result in using the default chrome driver and not the one set by the user.
If we add `chromedriverPath` to the destructured args and a user provides an invalid path we do error correctly throw the error as well as use the given Chrome driver: 
Invalid Path:
Valid Path: 
Note:  `--chromedriver-path` does not seem to support backwards compatibility in terms of Chrome Driver, it depends on your personal Chrome version. Example, if you're using V96 you cannot use V95 chrome driver, otherwise you will get a session error (as shown in the issue referenced).
Closes issue: …

fix(cli): pass chromedriver-path arg to webdriver

---

packages/cli/src/bin/cli.test.ts
packages/cli/src/bin/index.ts
packages/cli/src/lib/axe-test-urls.ts

The use of `--include` and providing an non-existent or invalid CSS selector would not notify user that was the case: 
Providing an non-existent or invalid CSS selector will now notify the user of said error: 
Closes issue: https://github.com/dequelabs/axe-core-npm/issues/207

fix(cli): provide a more robust error message if analysis fails

---

packages/cli/src/bin/index.ts
packages/cli/src/lib/axe-test-urls.ts
packages/cli/src/types.ts
packages/webdriverjs/src/index.ts
packages/webdriverjs/src/types.ts

This patch updates the error handling in `@axe-core/webdriverjs`, having it return an actual `Error` rather than a string. Rejecting/returning a string (eg `error.message`) leads to tons of bugs/confusion. Providing the `Error` to the caller enables a much richer debugging experience.
Closes #422
Ref #421
Ref #387
Ref #308 (somewhat)
Ref #207

fix(webdriverjs): Reject with actual `Error`s (not strings)

---

packages/cli/package-lock.json
packages/cli/package.json
packages/playwright/package-lock.json
packages/playwright/package.json
packages/playwright/src/index.ts
packages/playwright/src/utils.ts
packages/puppeteer/package-lock.json
packages/puppeteer/package.json
packages/puppeteer/src/axePuppeteer.ts
packages/puppeteer/src/utils.ts
packages/react/package-lock.json
packages/react/package.json
packages/reporter-earl/package-lock.json
packages/reporter-earl/package.json
packages/webdriverio/package-lock.json
packages/webdriverio/package.json
packages/webdriverjs/package-lock.json
packages/webdriverjs/package.json

closes issue: https://github.com/dequelabs/axe-core-npm/issues/434

feat: upgrade axe-core to 4.4.1

---

packages/react/index.ts

Had to cherry-pick PR to get CI running https://github.com/dequelabs/axe-core-npm/pull/437

fix(react):  fallback on _reactInternals

---

.circleci/config.yml

Update images due to [CircleCI deprecating old images](https://circleci.com/docs/2.0/next-gen-migration-guide/?mkt_tok=NDg1LVpNSC02MjYAAAGDBUMk7dU_Zxw5fNTv_3DBe5GFhHC4kabmviar7bwOL2wXKiq7WNQbs_o2L_ThnHD4j99jXTGTwwnzHGapRF42im_gQLAvhVukDaQX4qnHiOpcrw#overview)

ci: update circleci image

---

packages/react/cache.ts
packages/react/index.ts
packages/react/test/index.test.js

Fixing the accidental breaking change when we switched to use `export default` [instead of `export =`](https://github.com/dequelabs/axe-core-npm/pull/466/files#diff-037b868307272ef21e46ce4e727a16583b5d2ae66ed731296e7fc413b33e8832L415)

fix(react): revert export to not use default

---

packages/reporter-earl/tsconfig.json

Fixes the build so it doesn't add `src` and `test` in the `dist` directory and instead properly adds all src files as a direct child to `dist`. The tests didn't need to be built with TypeScript.

fix(reporter-earl): fix main export

---

.circleci/config.yml
packages/playwright/src/index.ts
packages/puppeteer/src/axePuppeteer.ts

Credit: https://github.com/dequelabs/axe-core-npm/pull/487
Had to check pick commit due to CI tests not running.

fix(puppeteer,playwright): wait for finishRun to complete before closing the page

---

.circleci/config.yml

Our [Changelog](https://github.com/dequelabs/axe-core-npm/blob/develop/CHANGELOG.md) is duplicating items between releases. We had a similar problem in axe-core and we were able to fix it by making sure the repo had the github tags properly set up (standard-release looks at the last github commit that pushed a tag to start the changelog diff process). By creating github releases that tag the commits, we should be able to fix the problem going forward.

ci: create github release for releases

---

CHANGELOG.md
packages/cli/CHANGELOG.md
packages/playwright/CHANGELOG.md
packages/puppeteer/CHANGELOG.md
packages/react/CHANGELOG.md
packages/reporter-earl/CHANGELOG.md
packages/webdriverio/CHANGELOG.md
packages/webdriverjs/CHANGELOG.md

The Changelog for each release hasn't been correctly putting the changed information (see #497). This goes back and updates all the Changelogs for each package (and the root) with what should be their relevant information.

chore: fix changelog with what actually changed since 4.4.0

---

packages/playwright/tests/axe-playwright.spec.ts
packages/puppeteer/test/axePuppeteer.test.ts
packages/webdriverio/src/test.ts
packages/webdriverjs/tests/axe-webdriverjs.spec.ts

Mostly, the pathing of the test fixtures were incorrect, so it was not testing the correct page.

test: playwright, puppteer, WDIO, and, WDJS tests

---

packages/webdriverio/package-lock.json
packages/webdriverio/package.json

We believe the issue that caused us to pin to 7.14.1 was this one https://github.com/webdriverio/webdriverio/issues/7994. Testing versions of webdriverio 7.14 - 7.19 no longer causes us any issues. The issue seems to have been resolved and we no longer need to pin to a specific version.

chore: update webdriverio peerDependency

---

packages/react/README.md

This patch is removing a section of documentation which downsells `axe-linter` (which operates on JSX, not actual DOM).

docs(react): Don't downsell axe-linter

---

packages/puppeteer/package-lock.json
packages/puppeteer/package.json
packages/puppeteer/src/axePuppeteer.ts
packages/puppeteer/src/legacy.ts
packages/puppeteer/src/utils.ts
packages/puppeteer/tsconfig.json

fix(puppeteer): support puppeteer v15

---

packages/puppeteer/package-lock.json
packages/puppeteer/package.json

Hi! I am looking to update puppeteer on my project, but axe-core's peer dep on puppeteer is blocking me. If this could be merged in before https://github.com/dequelabs/axe-core-npm/pull/544 is released, that would be great!

chore: update puppeteer to v16

---

packages/cli/package-lock.json
packages/cli/package.json
packages/playwright/package-lock.json
packages/playwright/package.json
packages/playwright/src/index.ts
packages/playwright/src/types.ts
packages/playwright/src/utils.ts
packages/playwright/tests/axe-playwright.spec.ts
packages/puppeteer/package-lock.json
packages/puppeteer/package.json
packages/puppeteer/src/axePuppeteer.ts
packages/puppeteer/src/utils.ts
packages/puppeteer/test/axePuppeteer.test.ts
packages/webdriverio/package-lock.json
packages/webdriverio/package.json
packages/webdriverio/src/index.ts
packages/webdriverio/src/test.ts
packages/webdriverio/src/utils.ts
packages/webdriverjs/package-lock.json
packages/webdriverjs/package.json
packages/webdriverjs/src/index.ts
packages/webdriverjs/src/utils/index.ts
packages/webdriverjs/tests/axe-webdriverjs.spec.ts
packages/webdriverjs/tests/example/package-lock.json
packages/webdriverjs/tests/example/package.json

Closes: https://github.com/dequelabs/axe-core-npm/issues/615

feat: support shadow dom selectors

---

packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/lib/webdriver.test.ts
packages/cli/src/lib/webdriver.ts
packages/webdriverjs/package-lock.json
packages/webdriverjs/package.json

Updated selenium webdriver to latest so we're not pinned anymore to an older version.
Closes https://github.com/dequelabs/axe-core-npm/issues/580

chore(ci,webdriverjs): update selenium-webdriver to latest

---

packages/webdriverio/README.md

https://github.com/dequelabs/axe-core-npm/issues/674
Not much to really be done here other than the readme message. The package itself is only used in tests, but can't be removed until we actually remove support.

feat(webdriverio): deprecate @wdio/sync support

---

packages/webdriverio/src/test.ts

The webdriverio CI job was failing with the error message:
session not created: This version of ChromeDriver only supports Chrome version 109
Current browser version is 111.0.5563.64 with binary path /usr/bin/google-chrome
Despite the job running the following steps:
- browser-tools/install-chrome
- browser-tools/install-chromedriver
- run: npm run coverage --prefix=packages/webdriverio
And browser-tools/install-chromedriver automatically installing the right version of chromedriver based on the previously installed chrome version.[1]
This was because browser-tools/install-chromedriver installed the chromedriver under /usr/local/bin/chromedriver while packages/webdriverio/src/test.ts was using the chromedriver from the chromedriver NPM package (which is currently set to ^109.0.0 in …

ci: fix webdriverio test using wrong chromedriver (#684

---

packages/cli/.eslintrc.js
packages/cli/src/bin/cli.ts
packages/cli/src/lib/webdriver.test.ts
packages/cli/src/lib/webdriver.ts
packages/cli/src/types.ts

The timeout was decreased in 6f5498ee8a2acb78846aa623773c7d1de19125e0 to 20 seconds (apparently accidentally since that commit was classfied as a refactor ... and it also didn't update the --help text accordingly).
This commit changes it back to 90 seconds to match the --help text.

fix(cli): increase --timeout default to 90 seconds (to match --help)

---

.circleci/config.yml
packages/webdriverio/src/test.ts
packages/webdriverjs/tests/axe-webdriverjs.spec.ts
packages/webdriverjs/tests/example/webdriverjs-example.ts
packages/webdriverjs/tests/test-utils.ts

This change helps prevent chromedriver version mismatches in the CI
by no longer requiring the chromedriver version in `package-lock.json`
to match the chrome version installed in the CI.
I already previously added similar logic in 3a38cf751636aa9846c77c580e21bb903b7185f6
for webdriverio. This commit improves that logic to no longer hard-code the chromedriver
path in the test and instead provide it via an environment variable (so it can also be used
to run the tests locally against a Chrome version different than the locked chromedriver version).
This commit additionally adapts webdriverjs and webdriverjs-example to also respect
this new CHROMEDRIVER_PATH environment variable.

refactor: make tests respect CHROMEDRIVER_PATH

---

packages/cli/package.json
packages/cli/src/lib/axe-test-urls.test.ts
packages/cli/src/lib/axe-test-urls.ts

Closes: https://github.com/dequelabs/axe-core-npm/issues/711

fix(cli): do not inject script tags due to pages not allowing script tags

---

packages/react/package.json

Closes: https://github.com/dequelabs/axe-core-npm/issues/719
Closes: https://github.com/dequelabs/axe-core-npm/issues/721
Testing for every project was done on the `.mjs` files themselves, so this was missed because it solely is about publishing.
There was some testing with the packaged tarball, but that was to ensure that the `exports` field of package.json was correct, not that the new files were exported, so it wasn't done on all packages.
Also, most of our stuff package the entire `dist` directory, so it was missed that `@axe-core/react` exports individual files.

fix(react): include .mjs file in publish

---

.circleci/config.yml

I noticed we do not depend on the CircleCI playwright job for canary / prod releases. if it fails, we will still publish.
We don't need to run tests again on the develop and master branch as we run tests on each PR
Closes: https://github.com/dequelabs/axe-core-npm/issues/739

ci: remove tests from the `develop` and `master` branch

---

packages/webdriverjs/src/index.ts
packages/webdriverjs/test/axe-webdriverjs.spec.ts
packages/webdriverjs/test/fixtures/iframe-lazy-1.html
packages/webdriverjs/test/fixtures/lazy-loaded-iframe.html

Closes https://github.com/dequelabs/axe-core-npm/issues/744

fix(webdriverjs): skip unloaded iframes

---

.eslintrc.js
packages/cli/src/lib/events.ts
packages/cli/src/lib/webdriver.ts
packages/cli/src/types.ts
packages/puppeteer/src/browser.ts
packages/reporter-earl/src/types.ts
packages/webdriverio/src/index.ts
packages/webdriverio/src/utils.ts
packages/webdriverio/test/axe-webdriverio.spec.ts
packages/webdriverjs/src/browser.ts
packages/webdriverjs/src/index.ts
packages/webdriverjs/src/utils/index.ts
packages/webdriverjs/test/axe-webdriverjs.spec.ts

People don't care about warnings. Unless a build fails, ESLint output will go unnoticed. This patch prevents that from happening by converting existing warnings to errors.
Also all existing warnings have been fixed.

chore: Make existing ESLint warnings fail the build

---

.github/workflows/tests.yml

We shouldn't let tests run for large amounts of time: https://github.com/dequelabs/axe-core-npm/actions/runs/5790182483/job/15692791377 in case of hanging.
Set a default timeout for linting at 5min and integration tests at 15mins.

ci: add default timeouts to test suite

---

packages/cli/package-lock.json
packages/cli/package.json
packages/webdriverio/package-lock.json
packages/webdriverio/package.json

Always use latest at the point of install / clone, no need to pin to a specific version

chore: use `latest` chromedriver where necessary

---

.github/workflows/deploy.yml

Lerna was generating SHAs that weren't compatible with npm tags. E.g `@axe-core/cli@4.7.4-alpha.0+8b5d296` which would be truncated to `@axe-core/cli@4.7.4-alpha.0` for npm.

ci: fix deploy sha

---

packages/webdriverjs/README.md

```
const driver = Builder()
^
TypeError: Class constructor Builder cannot be invoked without 'new'
```

docs(README): fix error in example script

---

.github/workflows/deploy.yml

with npm workspaces, we don't need `bootstrap` anymore

ci: remove `bootstrap` step from deploy workflow

---

.github/workflows/deploy.yml

Closes: https://github.com/dequelabs/axe-core-npm/issues/867

ci: add `release-candidate` to deploy.yml

---

.github/workflows/deploy.yml

This replaces the implemented GHA that cuts a release in GitHub since the GHA requires a git branch to have the tag `refs/tags/` and when we cut the release we do not use the version as part of the release process
```
- uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
```
with the GitHub CLI https://cli.github.com/manual/gh_release_create

ci: fix GH release workflow

---

.eslintrc.js
.github/workflows/tests.yml
package-lock.json
package.json
packages/webdriverio/src/utils.ts
packages/webdriverio/test/axe-webdriverio.spec.ts
test/wdio/package.json
test/wdio/tsconfig.json
test/wdio/wdio-globals.spec.ts
test/wdio/wdio.conf.ts

When using `@wdio/globals`, `browser` is a function and not an object (thanks wdio).
Closes: https://github.com/dequelabs/axe-core-npm/issues/798

fix(webdriverio): work with @wdio/globals

---

package-lock.json
package.json

These had to be done together. Supersedes #908

chore: bump @typescript-eslint/eslint-plugin and @typescript-eslint/parser from 5.62.0 to 6.9.1

---

.github/dependabot.yml

Commander [v10](https://github.com/tj/commander.js/releases/tag/v10.0.0) requires node 14, commander [v11](https://github.com/tj/commander.js/releases/tag/v11.0.0) requires node 16. Both are breaking changes in our supported Node versions.

chore: ignore commander dependabot updates

---

.github/workflows/tests.yml
packages/playwright/package.json
packages/playwright/test/commonjsTest.js
packages/playwright/test/esmTest.mjs
packages/puppeteer/package.json
packages/puppeteer/test/commonjsTest.js
packages/puppeteer/test/esmTest.mjs
packages/react/package.json
packages/react/setupGlobals.mjs
packages/react/test/commonjsTest.js
packages/react/test/esmTest.mjs
packages/react/test/setupGlobals.mjs
packages/reporter-earl/jest.config.js
packages/reporter-earl/package.json
packages/reporter-earl/tests/commonjsTest.js
packages/reporter-earl/tests/esmTest.mjs
packages/webdriverio/package.json
packages/webdriverio/test/commonjsTest.js
packages/webdriverio/test/esmTest.mjs
packages/webdriverjs/example.js
packages/webdriverjs/package.json
packages/webdriverjs/src/index.ts
packages/webdriverjs/test/commonjsTest.js
packages/webdriverjs/test/esmTest.mjs

This fixes the breaking change we accidentally released in 4.7.3 when we broke the default export of `@axe-core/webdriverjs`. Also added tests to ensure we don't make the same mistake again.
Closes https://github.com/dequelabs/axe-core-npm/issues/940

fix(webdriverjs): fix default commonJs export

---

packages/playwright/package.json
packages/playwright/test/tsTest.ts
packages/puppeteer/package.json
packages/puppeteer/test/tsTest.ts
packages/react/package.json
packages/react/test/tsTest.ts
packages/reporter-earl/package.json
packages/reporter-earl/tests/tsTest.ts
packages/webdriverio/package.json
packages/webdriverio/test/tsTest.ts
packages/webdriverjs/package.json
packages/webdriverjs/test/tsTest.ts

Add [typescript export tests](https://github.com/dequelabs/axe-core-npm/pull/927#pullrequestreview-1738072472) to all our packages. In so doing discovered https://github.com/dequelabs/axe-core-npm/issues/944.

test: test built types export

---

test/wdio/package.json

We run `npm run build -ws` and the `test/wdio` package did not have build script so would fail the deploy.
No QA needed.

ci: fix deploy pipeline

---

.github/dependabot.yml

* [tempy 2.0 is ESM only](https://github.com/sindresorhus/tempy/releases/tag/v2.0.0)
* [delay 6.0 is ESM only](https://github.com/sindresorhus/delay/releases/tag/v6.0.0)
No QA needed

chore: ignore esm package updates for delay and tempy

---

.github/dependabot.yml

[Chai 5.0.0 moved to ESM](https://github.com/chaijs/chai/releases/tag/v5.0.0).
Closes: https://github.com/dequelabs/axe-core-npm/pull/972

chore(dependabot): ignore esm chai >= 5.0.0

---

package-lock.json
packages/cli/package.json
packages/cli/src/lib/webdriver.test.ts
packages/cli/src/lib/webdriver.ts
packages/webdriverjs/test/test-utils.ts

[Selenium-webdriver@4.17.0](https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/CHANGES.md#4170) released a breaking change that removed the deprecated function to call `setHeadless` or `headless`. Fixed by using the [new `addArugments`](https://www.selenium.dev/blog/2023/headless-is-going-away/) with `--headless`, and feature detecting the function before calling it in order to support older versions of selenium.
Also patched pin to selenium-webdriver as [they do not follow semver](https://github.com/SeleniumHQ/selenium/issues/12241#issuecomment-1602282881) and can release breaking changes in minor versions.
Closes: https://github.com/dequelabs/axe-core-npm/issues/991

fix(webdriverjs): use new headless argument to fix selenium-webdriver@4.17.0 breaking release

---

README.md

This repo switched over to GHA from circleci
no qa required

chore: remove circleci badge

---

package-lock.json
packages/cli/package.json
packages/cli/src/lib/axe-test-urls.ts
packages/cli/src/lib/utils.test.ts
packages/cli/src/lib/webdriver.test.ts

Add a test to cover the event that users are using selenium-webdriver <4.17.0 and chrome options use the "old" way of supporting headless runs. Also did some cleanup and removed code that wasn't required in cli
no qa required

test(cli): add test to cover selenium-webdriver <4.17.0

---

package-lock.json

Fixes the broken lazy load iframe tests.
Ref: https://github.com/dequelabs/axe-core-npm/pull/1052
No QA needed.

chore: update test-fixtures to fix lazy load iframe

---

package-lock.json
packages/playwright/package.json
packages/playwright/src/index.ts
packages/playwright/test/axe-playwright.spec.ts

Pulled out of https://github.com/dequelabs/axe-core-npm/pull/1048. Starting in Playwright 1.41.0 (using Chrome version 121.0.6167.57) Playwright is no longer loading the lazy loaded iframe that is out of view. Updated the version  of Playwright and updated the tests to now account for this.
QA notes: Test a lazy loaded iframe with Playwright > 1.41.0 and ensure Playwright will complete an analyze of the page

fix(playwright): skip unloaded iframes

---

packages/playwright/src/index.ts

Hi,
This missing await causes us many, hard to debug problems, when page has been closed prematurely (popup or terminating analysis if too long)
Simple reproduction :
```ts
(async () => {
const browser = await playwright.chromium.launch({ headless: true });
const context = await browser.newContext();
const page = await context.newPage();
await page.close();
try {
const results = await new AxeBuilder({ page }).analyze();
console.log(results);
} catch (error) {
console.error(error);
}
await browser.close();
})();
// node:internal/process/promises:279
triggerUncaughtException(err, true /* fromPromise */);
^
page.evaluate: Target page, context or browser has been closed
```
I haven't been able to write a simple test that reproduce the problem but I can reproduce it in my project and adding …

fix(playwright): Add missing await on page.evaluate

---

.github/workflows/tests.yml
package-lock.json
package.json
packages/cli/README.md
packages/cli/src/bin/index.ts
packages/cli/src/lib/utils.ts
packages/cli/src/lib/webdriver.test.ts
packages/cli/src/lib/webdriver.ts
packages/puppeteer/test/esmTest.mjs
packages/puppeteer/test/utils.ts
packages/webdriverio/README.md
packages/webdriverio/package.json
packages/webdriverio/test/axe-webdriverio.spec.ts
packages/webdriverjs/README.md
packages/webdriverjs/package.json
packages/webdriverjs/test/test-utils.ts

chore: use updated browser-driver-manager

---

.github/dependabot.yml
.github/workflows/deploy.yml
package-lock.json
package.json

chore: downgrade lerna to resolve ESM requirement

---

package-lock.json
packages/cli/package.json

fix(cli): include `dotenv` dep

---

packages/webdriverio/README.md

Update README to ensure the community is aware of a possible issue with the bidi protocol which is the new default within WebDriverIO v9.
QA notes: No QA needed.

docs(webdriverio): bidi support notice

---

packages/playwright/src/index.ts

If `AxeBuilder` is instantiated many times, each instance of the class will store the 250kb axe source string causing performance issues.
I looked at `@axe-core/puppeteer` and they follow the pattern in this PR:
- https://github.com/bensenescu/axe-core-npm/blob/develop/packages/puppeteer/src/axePuppeteer.ts#L59
- https://github.com/bensenescu/axe-core-npm/blob/develop/packages/puppeteer/src/utils.ts#L34
No QA required

fix: Optimize AxeBuilder memory usage.

---

packages/webdriverio/package.json

chore(wdio): add webdriverio ^9 to peer dependencies
